### ISSUE TITLE
Linter disabled for both dev server and IDE

### ISSUE THREAD

**Issue by aChanEP** [elasticpath/react-pwa-reference-storefront#341]
### Step 2: Describe your environment

  * Device: MACOSX
  * OS version: 10.14.5
  * Storefront pulled version: 1dd83942904b78655c194b2ebeedecd222989f69
  * Node version: v11.13.0
  * Docker version: _____
  * Docker Compose version: _____

### Step 3: Describe the problem:

The linter is not working for both the web application and storybook.  Can try a simple test by uncommenting an `eslint disable ..` line and see that the webpack live bundler does not pick up any linter violations.  Can also write a `console.log` in any files (a common airbnb standard violation) and no linter errors appear.  Upon inspecting the webpack config files you can see that the linter sections are commented out.  Uncommenting these lines does indeed turn the linter back on, atleast for the CRA dev server.  

Further, there is no .eslintrc file in the project and so the vscode eslint plugin does not pick up eslint errors right in the ide.

#### Steps to reproduce:

  1. Write eslint violations

#### Observed Results:

  * no violations

#### Expected Results:

  * no violations were not caught in both the ide and the dev servers.

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by RSsupport** [comment]
<https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zi38W3MHKn9TromRluIPEBd78N5DX-CL4bddNqppWDXtv6sUfk0ilP0c3ze0e6UeHOBI=>
Hi there

You previously expressed interest in Elastic Path, but it's been a while since we've been in touch. So, we wanted to pass along some of our most popular content for eCommerce innovators we thought you might find interesting. Stay connected to receive:


	- Exclusive analyst reports like Gartner's 2021 Predictions <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zixaz5j-ujLDs0prag3mGEHUeHEt0jlyZAkjxuR3stD0TlK3CRH2zrn3PPi3VjflLTgU=>
	- The latest B2B commerce insights from Brian Beck <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zi0Vqw4Q59_leRRpegHuQOHIs4GJPbq7c0mIEa1I4cH18mhqyJT_gvRDIGM81AyEg0R4=>
	- Future trends uncovered in our Sci-Fi Shopper ebook <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zi_-3ZSv4afIVCDXXla4r0PCm8qBH3K5vnmvF-xXn06XLREDqG4Nx2IbHQTbDDDog-l8=>



Let us know that you'd like to stay in touch by clicking the link below.  Otherwise, you can update your preferences to unsubscribe here <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54ZizA0_Vpw6ePdO8-R8DOBEFP79kHbkpQ0ecbnPARayE9mPy-Txr1wsSWcggo8ZyEdaSw=> - and we'll be sad to see you go.
Gartner Predicts 2021: COVID-19 Drives Accelerated Shift to Digital and Commerce Model Evolution
Explore the latest digital commerce predictions from Gartner to strengthen your 2021 strategy and future-proof your business. 

Read the full Report.>> <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zixaz5j-ujLDs0prag3mGEHUeHEt0jlyZAkjxuR3stD0TlK3CRH2zrn3PPi3VjflLTgU=>
Seize the Billion Dollar B2B Commerce Opportunity with Brian Beck
Check out the latest video series from Brian Beck and industry experts to learn how to evolve and grow a multi-billion dollar business.  development.

Watch the Series.>> <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54Zi0Vqw4Q59_leRRpegHuQOHIs4GJPbq7c0mIEa1I4cH18mhqyJT_gvRDIGM81AyEg0R4=>
<p style="margin-top: 10px; margin-bottom: 10px; text-align: center;">Copyright &copy; 2020 Elastic Path Software, All rights reserved.<br /><span>United States&nbsp;Office:<span>&nbsp;Fifth&nbsp;</span></span>Floor, 200 Portland St, Boston, MA, 02114, US&nbsp;<br /></p>
If you no longer wish to receive these emails you may unsubscribe <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAF9j54ZizA0_Vpw6ePdO8-R8DOBEFP79kHbkpQ0ecbnPARayE9mPy-Txr1wsSWcggo8ZyEdaSw=> at any time.

If you no longer wish to receive these emails you may update your preferences here: https://pages.elasticpath.com/UnsubscribePage.html?mkt_unsubscribe=1&mkt_tok=OTAxLUtTVy05OTMAAAF9j54ZjIuh_i_leJag5AARJMWvDAUxC7Qd1Ugcutnn4cXTTjyYOea1vjnsA1LEsnrqmRQ4CkVslt_l9VwSndPtzBQrdFU6f4_qIjbd5U3bjQc.

**Comment by RSsupport** [comment]
DZONE TREND REPORT
Software Integration

  READ REPORT <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iWLIlQB3I6kz_jdDhlVpYbM2ih4O-sRaXxWSfZJ4N8eSZuKTnp7O1F3E_clpaHwFR7Q=>
The Intersection of APIs, Microservices, and Cloud-Based Systems
Integrating different systems in an efficient, cost-effective, and user-friendly manner is a constant struggle. Check out the recent Software Integration Trend Report to discover how developers, architects, and other IT professionals today are addressing these challenges and understand the current state of software integration.

A few key insights:




	- 56% of survey respondents said their organization integrated at least four systems.
	- While 68% favored a microservice-based architecture, there is still much room for adoption.
	- On average, respondents spent 39% of their time managing API integrations.
${btnLinkText} <[[${btnLink}]]>
Boston, USA Office 
4th Floor, 200 Portland St 
Boston, MA 02114
<https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7ibMNiZc5Io7brzDYUWPi3iVteq9xrOQQxlX3lmJ_VbCX_NW9C8HvUFhFL_VVkJl3PQM=>   <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iRerD-OiQLaMJtky_Qgw8OhxVTrV812bYmjOZNa0rmuZkxHnsQiLRbYJnx62dcAHc9Y=>   <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iWo5a41_j5w3TcVpzgxGjYNXNGdh_V7b-Mw9Qnc9uQKqVP7Bpulj9ZIdi4N4OgdNjno=>   <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iY-dJ7GQMGGAQIBrIZavnauMP15rv8FnQRBqGHdP1e_IhskRuQMGz0csgdGii3gIszA=>
Terms of Use <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iS8cW357vZUvE1iqnKJr2Pdi1rQPJRB518VU8HYaGpMFJwEPHSx4d7xxuQbnpMBUwsA=>  |  Privacy & Policy <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGM48u7iVUn-Luzn3XdjDJO6i7m5iAdGGiVSWrZmJfBOeDdmOguDxHaT24GmnshZLZpStRf_Q8=>  |  Unsubscribe <[[https://pages.elasticpath.com/UnsubscribePage.html?mkt_unsubscribe=1&mkt_tok=OTAxLUtTVy05OTMAAAGM48u7iSzQZKsfDRKu0S8rMExkjzcFDLspqNdKAVDUP6a6RXyno7haLk7_z8LGzrx4Q87PZsaTbmzEHe5iNfEe37E5yPy_yoe_SdpEC9YwsM8]]>
Copyright © 2023, Elastic Path Software Inc. All rights reserved.

**Comment by RSsupport** [comment]
Are you facing the challenge of delivering innovative buying experiences while managing the constraints of technology, time, and budget? You're not alone. Join us for a Live Roundtable: Tech Execs Take on Commerce in 2025 <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3Oy5lvB5NT1OvlitYH9mGtA1fsXnNb2TET2gbTUoa-WjxAocbiMLheONpqVqMA0J8kJA=> where we bring together leaders from Comcast, Astrak, and Vivrelle to discuss:




	- How they’ve tackled the unique challenges of commerce in manufacturing and retail.
	- What’s on their roadmap for 2025.
	- Key advice for tech execs evaluating commerce replatforming.



PS - Even if you can't join live, register to get the recording!
<https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3Oy5lvB5NT1OvlitYH9mGtA1fsXnNb2TET2gbTUoa-WjxAocbiMLheONpqVqMA0J8kJA=>
Boston, USA Office 
4th Floor, 200 Portland St 
Boston, MA 02114
<https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3O6Onp7UBfFafX957f0vKRCJfTEeYbiUHu6AQQZz2qwnGqx_xNtJe73cgkQT9S7B-EC0=>    <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3OxSK8elfkNZvgmd-m8IM9tBMLFCZ2TQFHwDOCA_Z1jIHeVTAoQQgKu5dhZrDOovjtlw=>    <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3O00QU9kq6NFt6aVZCmVsNLMUwTdF55AfFOXn6e4t7KSYaV9lsBJpq2XoSV9D_2KUQl8=>    <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3Ozc2zGUkG02G0WjbZzbUiGLjptXmOcTnVFhA5zcTfHDnp0mWMa7Wj5SU9Fp2ZQ7jr_c=>
Terms of Use <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3Ozi5sdsgYDst0a9YXDg_IHJRAo9DG2vvlHNE6bg8eYxql-XCClQUlIWkn0IQ7tjFFwo=>  |  Privacy & Policy <https://info.elasticpath.com/OTAxLUtTVy05OTMAAAGWFzR3O2gqaxsTnLFj36TpC1leIKQHIPi3R5R8j-NRbM3t3NHXud6w7RVS4VXZbtzWMnT8Wos=>  |  Unsubscribe <[[https://pages.elasticpath.com/UnsubscribePage.html?mkt_unsubscribe=1&mkt_tok=OTAxLUtTVy05OTMAAAGWFzR3O8Wm982FvU2D47gvnjwjHPz3rT5RHOPWpZL9X2rdR2l-o-_ypZgWAxfsXIfui1QqxLzgkMXM_jcweSTTgIxtZl8btmaiRSzciBqGNyo]]>
Copyright © 2024, Elastic Path Software Inc. All rights reserved
